<?php
// DI CODE - Start
namespace Database\Seeders;

use Illuminate\Database\Seeder;

// Newly Added
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use App\Models\Ad;

class AdSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		//Ad::truncate();

        $items = [
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '3',
            'ad_sub_category_id' => '6',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '3',
            'ad_sub_category_id' => '6',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '3',
            'ad_sub_category_id' => '6',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '3',
            'ad_sub_category_id' => '6',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '3',
            'ad_sub_category_id' => '6',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '3',
            'ad_sub_category_id' => '6',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '3',
            'ad_sub_category_id' => '6',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '3',
            'ad_sub_category_id' => '6',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '3',
            'ad_sub_category_id' => '6',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '3',
            'ad_sub_category_id' => '6',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '3',
            'ad_sub_category_id' => '6',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '3',
            'ad_sub_category_id' => '6',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '3',
            'ad_sub_category_id' => '6',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '9',
            'ad_sub_category_id' => '11',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '9',
            'ad_sub_category_id' => '11',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '9',
            'ad_sub_category_id' => '11',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '9',
            'ad_sub_category_id' => '11',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '9',
            'ad_sub_category_id' => '11',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '9',
            'ad_sub_category_id' => '11',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '9',
            'ad_sub_category_id' => '12',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '9',
            'ad_sub_category_id' => '12',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '9',
            'ad_sub_category_id' => '12',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '9',
            'ad_sub_category_id' => '12',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '9',
            'ad_sub_category_id' => '12',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '9',
            'ad_sub_category_id' => '12',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '9',
            'ad_sub_category_id' => '12',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '9',
            'ad_sub_category_id' => '12',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '9',
            'ad_sub_category_id' => '12',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '9',
            'ad_sub_category_id' => '12',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '10',
            'ad_sub_category_id' => '13',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '10',
            'ad_sub_category_id' => '13',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '10',
            'ad_sub_category_id' => '13',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '10',
            'ad_sub_category_id' => '13',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '10',
            'ad_sub_category_id' => '13',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '10',
            'ad_sub_category_id' => '13',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '10',
            'ad_sub_category_id' => '13',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '10',
            'ad_sub_category_id' => '13',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '10',
            'ad_sub_category_id' => '13',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '7',
            'ad_sub_category_id' => '14',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '7',
            'ad_sub_category_id' => '14',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '7',
            'ad_sub_category_id' => '14',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '7',
            'ad_sub_category_id' => '14',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '7',
            'ad_sub_category_id' => '14',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '7',
            'ad_sub_category_id' => '14',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '7',
            'ad_sub_category_id' => '14',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '7',
            'ad_sub_category_id' => '14',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '7',
            'ad_sub_category_id' => '14',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '7',
            'ad_sub_category_id' => '14',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '7',
            'ad_sub_category_id' => '14',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
			[
            'ad_title' => Str::random(10),
            //'slug' => Str::random(10),
            'ad_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            'ad_category_id' => '7',
            'ad_sub_category_id' => '14',
            'ad_condition' => 'new',
            'ad_price' => '458',
            'ad_user_id' => '1',
            'ad_seller_name' => Str::random(10),
            'ad_seller_email' => Str::random(10).'@test.com',
            'ad_seller_phone' => '9876543210',
            'created_at' => date('Y-m-d h:i:s'),
            'updated_at' => date('Y-m-d h:i:s'),
			],
        ];

        foreach ($items as $item) {
            Ad::create($item);
        }
		
       
    }
}
// DI CODE - Start